title: "Denz Del Villar"
tagline: "Research Software Engineer · Mobile Health · Simulation"
theme: minima

author:
  name: "Denz Del Villar"
  email: "denzdelvillar@gmail.com"
  github: "denzdelvillar"
  url: "https://github.com/denzdelvillar"

header_pages:
  - index.md
  - projects.md
  - resume.md
  - cv.md

minima:
  social_links:
    github: denzdelvillar
    email: denzdelvillar@gmail.com
