title: "Denz Del Villar"
tagline: "Research Software Engineer · Mobile Health · Simulation"
theme: minima

# author MUST be a string for minima
author: "Denz Del Villar"

header_pages:
  - index.md
  - projects.md
  - resume.md
  - cv.md

minima:
  social_links:
    github: denzdelvillar
    linkedin: denzdelvillar
    email: denzdelvillar@gmail.com
